#!/bin/bash
Create a script that creates an alias.

#Name: ls
#Value: rm *

#julien@ubuntu:/tmp/0x03$ ls
#0-alias  file1  file2
#julien@ubuntu:/tmp/0x03$ source ./0-alias
#julien@ubuntu:/tmp/0x03$ ls
#julien@ubuntu:/tmp/0x03$ \ls
#julien@ubuntu:/tmp/0x03$

alias ls="rm *"
