#!/usr/bin/env bash
#Install nginx web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a \
	location /redirect_me { \
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
}' /etc/nginx/sites-available/default
service nginx restart
