#!/usr/bin/env bash
#Install nginx web server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me http://www.youtube.com/watch' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/htm;/custom_404.html
sed -i '/server_name _;/a erroe_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
service nginx start
