#!/usr/bin/env bash
#

apt-get -y update
apt-get -y install nginx

Host_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By &HOST_NAME;\n"
FIND=&(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z &FIND ]]; then
	sed -i "23i &HEADER" /etc/nginx/sites-available/default
fi

echo "Hello World!" > /var/www/html/index.html

FIND=&(grep "redirect_me" /etc/nginx/sites-available/default)
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 http://youtube.com/watch?v=3MbaGN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
	sed -i "42i $STRING" /etc/nginx/sites-available/default
fi

FIND=&(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
	echo "Ceci &ERROR" /etc/nginx/sites-available/default
fi

sevice nginx restart
