#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80.

#rm /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default 
ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
service nginx restart
