#!/usr/bin/env bash
#previous exercise, Bash script displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process
#You cannot use pgrep
#shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
