#!/usr/bin/env bash
#Bash script that displays Best School 10 times.

while IFS=':' read -r username x uid gid info homedir shell; do
	echo "The user &username is part of the $gid gang, lives in &homedir and rides &shell. $uid`s place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd
