#!/usr/bin/env bash
#Bash script that displays Best School 10 times.

for file in $(ls); do
	if [[ $file != .* && $file == *-* ]]; then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
