#!/usr/bin/env bash
#Bash script that displays Best School 10 times.

shopt -s nullglob
for file in *; do
	if [[ $file != .* && $file == *-* ]]; then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	else
		echo "$file"
	fi
done
