#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.

#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/temp
sudo sed -i 's/127.0.0.1[[:space:]]\+loclhost/127.0.0.2\tlocalhost/' /etc/hosts
sudo sed -i 's/157.240.11.35[[:space:]]\+facebook.com/8.8.8.8\tfacebook.com/' /etc/hosts


sudo service networking restart
echo "restart system"
