#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.

#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/localhost ~/localhost.new
sed -i 's/127.0.0.1/127.0.0.2' ~/localhost.new
sed -i '2i8.8.8.8 facebook.com' ~/localhost.new
cp -f ~/localhost.new /etc/localhost
