#!/usr/bin/env bash
# fix
sed -i '/Listen 80/a Listen 0.0.0.0:8080' /etc/apache2/ports.conf
sed -i 'VirtualHost>/a <VirtualHost *:8080>\nServerAdmin webster@localhost\nDocumentRoot /var/www/html\n</VirtualHost>' /etc/apache2/sites-available/000-default.conf
service apache2 start
